/**
 * The /training-course table's horizontal geometry — the widths only.
 *
 * Dependency-free (no React, no next/*) so the `pure` tier can check the
 * numbers without a DOM, the same reason lib/schedule/scheduleTableLayout.js
 * is. jsdom does not do layout, so no test here can measure a rendered column;
 * what CAN be pinned is that the column set is well-formed and that the table's
 * floor is the SUM of the array rather than a number written down beside it.
 *
 * ── THE DEFECT THIS FIXES ───────────────────────────────────────────────────
 * Every program group renders its own `<table>` (CourseListClient maps over
 * `groups`), and the table carried no `table-fixed`, no `<colgroup>` and no
 * width on any `<th>`. That is browser AUTO layout, which sizes columns from
 * each table's OWN content — so the Power BI group and the Microsoft Excel
 * group computed different widths and โปรแกรม / วัน / ชม. visibly sheared from
 * one group to the next down the page. Nothing made them agree because nothing
 * was shared between them. These widths are that shared thing.
 *
 * ── THE WIDTHS WERE MEASURED, NOT CHOSEN ────────────────────────────────────
 * Method per scheduleTableLayout: sum glyph advance widths out of the shipped
 * font's `hmtx` at the type the cell actually renders at. Character counting is
 * wrong for Thai — above/below vowels and tone marks are ZERO-ADVANCE, so
 * `ราคา (บาท / ท่าน)` is 17 codepoints of which only 16 move the pen.
 *
 * THE FONT IS GOOGLE SANS, NOT LINE SEED, and that is a real difference from
 * /schedule. globals.css says `label, input, select, textarea, button, li, td,
 * th { @apply font-en; }`, `font-en` is ["Google Sans", var(--font-en),
 * sans-serif] with no LINE Seed in the stack, and the `:lang(th) → font-thai`
 * rule below it is commented out. Google Sans does cover Thai (verified against
 * its cmap), so the fallback never fires and these cells render in Google Sans.
 * Measuring against LINESeedSansTH_W_Bd — the binary /schedule was measured
 * against — would have produced numbers for a font this table never uses.
 *
 * Measured at 14px (the table's `text-sm`), weight per the cell's own class,
 * against the real course list (78 courses):
 *
 *   column    header @700   widest cell content        content   +32px pad
 *   ────────────────────────────────────────────────────────────────────────
 *   โปรแกรม        52.6     "Microsoft PowerPoint" 136.8@400     136.8  168.8
 *   วัน            15.1     "4"                      8.3@400      15.1   47.1
 *   ชม.            20.4     "30"                    16.5@400      20.4   52.4
 *   ราคา (…)       97.7     "Inhouse Only"          86.5@600      97.7  129.7
 *
 * `px-4` on every cell is 32px of the box, which is why each width is content
 * plus 32. Two of the four are driven by the HEADER and two by the DATA, which
 * is exactly why both had to be measured rather than one assumed to dominate.
 *
 * The widest program name is "Microsoft PowerPoint" (136.8px), NOT "Microsoft
 * Excel" (97.0px) — the group that looked widest on screen was not the one with
 * the longest name, and assuming Excel would have under-sized this column by
 * 40px.
 */

/**
 * The floor the wrapping ชื่อหลักสูตร column may shrink to.
 *
 * It carries NO fixed width: under `table-fixed` a `<col>` with no width
 * absorbs whatever the other four leave, so on a wide viewport the course name
 * takes all the slack. This floor exists only to feed the table's `min-width`,
 * which is what makes a NARROW screen scroll instead of squashing all five
 * columns toward zero. 320 leaves 288px of content box, which fits the median
 * course name (244.1px @14px/500) on one line and wraps the long ones — which
 * is the accepted trade: the name wraps, it never truncates.
 */
export const NAME_MIN_WIDTH = 320;

/**
 * The five columns, left to right. THE ONLY PLACE THESE WIDTHS EXIST.
 *
 * Labels and alignment live here too so the `<colgroup>`, the `<th>` row and
 * the `<td>` row cannot fall out of order with one another — all three are
 * generated by mapping this array. An off-by-one between them would put the
 * course name under the โปรแกรม heading, and no width check would catch that.
 *
 * `width: null` marks the single flexible column. Exactly one column may be
 * flexible; two would divide the slack between them and the table would stop
 * being predictable from group to group, which is the bug being fixed.
 *
 * The `align` strings are real Tailwind class literals and this file is inside
 * `./src/lib/**`, which tailwind.config.js scans — see the comment there about
 * the schedule-status colours that silently vanished when a class map moved
 * into an unscanned file.
 */
export const COLUMNS = [
  { key: 'name',    label: 'ชื่อหลักสูตร',      width: null, align: 'text-left'   },
  { key: 'program', label: 'โปรแกรม',           width: 176,  align: 'text-left'   },
  { key: 'days',    label: 'วัน',               width: 56,   align: 'text-center' },
  { key: 'hours',   label: 'ชม.',               width: 56,   align: 'text-center' },
  { key: 'price',   label: 'ราคา (บาท / ท่าน)', width: 136,  align: 'text-right'  },
];

/**
 * The table's `min-width` — DERIVED, so it cannot disagree with the array.
 *
 * The flexible column contributes its floor; every other column contributes its
 * fixed width. 320 + 176 + 56 + 56 + 136 = 744.
 *
 * Applied as an inline style rather than `min-w-[744px]`, for the reason
 * scheduleTableLayout's header documents: arbitrary Tailwind values must be
 * STATIC STRINGS because the compiler scans source text and never evaluates it,
 * so `min-w-[${n}px]` emits no class at all and fails silently. A hand-written
 * `min-w-[744px]` literal would compile — but it would be a SECOND place the
 * number lives, free to drift the moment a width here changes. Deriving it and
 * passing it inline keeps one source of truth and sidesteps the trap entirely.
 */
export const TABLE_MIN_WIDTH = COLUMNS.reduce(
  (sum, c) => sum + (c.width ?? NAME_MIN_WIDTH),
  0,
);

/**
 * Everything that must be true of a column set for the table to render sanely.
 *
 * Returns an array of complaints; empty means well-formed. A function rather
 * than assertions inline in the test so the test can run it against a MUTATED
 * array and prove the check can actually fail — a guard that only ever sees the
 * real, correct array is decoration.
 *
 * @param {Array} columns
 * @param {number} expectedCount how many columns the table is designed to have
 * @returns {string[]}
 */
export function columnProblems(columns, expectedCount = 5) {
  const problems = [];

  if (!Array.isArray(columns)) return ['columns is not an array'];

  if (columns.length !== expectedCount) {
    problems.push(
      `expected ${expectedCount} columns, got ${columns.length} — the colgroup, ` +
        'the header row and the body row are all generated from this array, so a ' +
        'missing entry drops a whole column rather than just a width',
    );
  }

  const flexible = columns.filter((c) => c.width === null || c.width === undefined);
  if (flexible.length !== 1) {
    problems.push(
      `expected exactly 1 flexible column, got ${flexible.length} — under ` +
        'table-fixed the slack is divided between every widthless column',
    );
  }

  for (const c of columns) {
    if (!c.key) problems.push(`a column has no key: ${JSON.stringify(c)}`);
    if (!c.label) problems.push(`column "${c.key}" has no label`);
    if (!c.align) problems.push(`column "${c.key}" has no alignment class`);
    if (c.width !== null && c.width !== undefined && !(c.width > 0)) {
      problems.push(`column "${c.key}" has a non-positive width: ${c.width}`);
    }
  }

  const keys = columns.map((c) => c.key);
  if (new Set(keys).size !== keys.length) {
    problems.push(`duplicate column keys: ${keys.join(', ')}`);
  }

  return problems;
}
