/**
 * GENERATED by scripts/backfill-upload-blob.mjs — DO NOT EDIT BY HAND.
 *
 * Legacy files served from Vercel Blob instead of Cloudinary, because Cloudinary
 * cannot hold them: its raw ceiling is 10 MB on any plan this project would
 * consider, and one of these is 42.6 MiB. The five MP3s are here for a second
 * reason as well — `mp3` is in neither IMAGE_EXTENSIONS nor RAW_EXTENSION_LIST,
 * so the Cloudinary rewrite has no rule that could serve them and the image
 * catch-all would ask for `image/upload/….mp3` and fail.
 *
 * ── WHY THIS FILE EXISTS AT ALL ─────────────────────────────────────────────
 * Cloudinary delivery is derived BY PATTERN: public_id IS the legacy path, so a
 * handful of rules serve 2,900 files with no lookup and no per-file maintenance.
 * Blob has no such property. A blob pathname is whatever it was named, so each
 * file needs its own rewrite — and a list of rewrites that a human keeps in step
 * with a list of uploaded objects is a list that drifts. Generating it from the
 * upload run makes the two the same fact.
 *
 * The pathnames still MIRROR the legacy path, so the mapping is readable and a
 * re-upload is idempotent; `blobPathname` is simply the public path without its
 * leading slash. That is a convention, not something next.config may assume —
 * it reads this array.
 *
 * next.config.mjs emits ONE rewrite per entry to
 * `${BLOB_PUBLIC_BASE}/${blobPathname}`, placed BEFORE the /files/ and /images/
 * catch-alls so these win. Regenerate with:
 *
 *   node --env-file=.env.local scripts/backfill-upload-blob.mjs --apply
 */

/** @type {ReadonlyArray<{ publicPath: string, blobPathname: string }>} */
export const LEGACY_BLOB_FILES = Object.freeze([
  { publicPath: "/files/9expert-roadmap-2023.pdf", blobPathname: "files/9expert-roadmap-2023.pdf" },
  { publicPath: "/files/9expert-training-course-catalog-2016.pdf", blobPathname: "files/9expert-training-course-catalog-2016.pdf" },
  { publicPath: "/files/9expert-training-course-catalog-2017-01.pdf", blobPathname: "files/9expert-training-course-catalog-2017-01.pdf" },
  { publicPath: "/files/9expert-training-course-catalog-2017-02.pdf", blobPathname: "files/9expert-training-course-catalog-2017-02.pdf" },
  { publicPath: "/files/company-profile.pdf", blobPathname: "files/company-profile.pdf" },
  { publicPath: "/files/powerpoint/gradient-theme.zip", blobPathname: "files/powerpoint/gradient-theme.zip" },
  { publicPath: "/files/powerpoint/gray-theme.zip", blobPathname: "files/powerpoint/gray-theme.zip" },
  { publicPath: "/images/asset/TemperatureGlass.png", blobPathname: "images/asset/TemperatureGlass.png" },
  { publicPath: "/images/audio/01-Vision-AI-ElonMusk.mp3", blobPathname: "images/audio/01-Vision-AI-ElonMusk.mp3" },
  { publicPath: "/images/audio/02-An-Honest-Conversation-on-AI-and-Humanity-YuvalNoahHarari.mp3", blobPathname: "images/audio/02-An-Honest-Conversation-on-AI-and-Humanity-YuvalNoahHarari.mp3" },
  { publicPath: "/images/audio/03-Productivity-with-AI-SatyaNadella.mp3", blobPathname: "images/audio/03-Productivity-with-AI-SatyaNadella.mp3" },
  { publicPath: "/images/audio/04-The-Day-after-AGI.mp3", blobPathname: "images/audio/04-The-Day-after-AGI.mp3" },
  { publicPath: "/images/audio/05-Jensen-Huang.mp3", blobPathname: "images/audio/05-Jensen-Huang.mp3" },
  { publicPath: "/images/next-skills/next-skills1.png", blobPathname: "images/next-skills/next-skills1.png" },
  { publicPath: "/images/next-skills/next-skills2.png", blobPathname: "images/next-skills/next-skills2.png" },
  { publicPath: "/images/next-skills/next-skills3.png", blobPathname: "images/next-skills/next-skills3.png" },
]);
