// src/lib/chat/rateLimit.js
//
// SERVER ONLY. Imported by the /api/chat route handlers. Never import this from
// a client component: the counters live in one server process's module scope
// and mean nothing in a browser.
//
// ── READ THIS BEFORE TRUSTING IT ─────────────────────────────────────────────
// THIS IS A SPEED BUMP, NOT A LIMIT. Saying otherwise would be a lie about the
// protection the site has.
//
// The counters live in the memory of ONE serverless instance. Vercel runs as
// many instances as it likes and recycles them freely, so:
//
//   · a caller spread across N warm instances gets N x `max` requests per
//     window, and nothing here can see that — each instance's Map is private;
//   · a cold start resets every counter to zero;
//   · anyone who actually wants the quota just opens enough connections that
//     the platform hands them a fresh instance.
//
// What it DOES buy, and the only reason it exists: a single client stuck in a
// retry loop, or one person holding Enter down, stops burning money on the paid
// LLM backend sitting behind /api/chat. That failure is common, accidental, and
// this stops it. A deliberate attacker is NOT in scope and must not be claimed.
//
// A durable limiter (Redis / Upstash / a Mongo TTL collection) is the real
// answer if this ever needs to be one. That is a deliberate decision with an
// infrastructure cost and an owner — it is NOT to be added as a side effect of
// shipping a chat widget.
//
// ── THE IDENTITY IS ALSO WEAK, AND FOR A DIFFERENT REASON ────────────────────
// `sessionId` is generated by the browser and stored in localStorage, so a
// caller who wants a fresh bucket just makes up a new one. It is therefore the
// LAST fallback, never the first choice. The forwarded IP is better but not
// good: mobile carriers and corporate NATs put thousands of unrelated people
// behind one address, so a busy shared egress can throttle innocent users. That
// trade is accepted here because the ceiling is set well above human typing
// speed — see DEFAULT_MAX.

const DEFAULT_WINDOW_MS = 60_000;

// Generous on purpose. A person conversing sends single-digit messages per
// minute; 15 leaves room for quick-reply chip tapping without ever being felt.
// The runaway-client case this guards against does hundreds.
const DEFAULT_MAX = 15;

// Cap on distinct keys held per instance, so a spray of forged session ids
// cannot grow the Map without bound. Eviction is oldest-reset-first.
const MAX_TRACKED_KEYS = 5_000;

/** key -> { count, resetAt } */
const buckets = new Map();

/**
 * Memory eviction. NOT the expiry mechanism — see the note below.
 *
 * Only runs once the Map is over its cap, which for any real traffic level is
 * never. Expired entries are dropped first (they are free to lose); if that is
 * not enough, whatever resets soonest goes next.
 *
 * ── THIS USED TO SWEEP EXPIRED BUCKETS ON EVERY CALL, AND THAT WAS A BUG ─────
 * Not a behavioural bug — a bug in how many places one rule lived. The sweep
 * ran unconditionally at the top of checkRateLimit, so by the time the per-key
 * `resetAt <= now` check below was reached, an expired bucket had ALREADY been
 * deleted and that check could never fire. Two implementations of "the window
 * has passed", one of them dead, and the window's release silently depending on
 * whichever ran first.
 *
 * It was found by a control, not by review: breaking the per-key check reddened
 * NOTHING, because the sweep was quietly covering for it. A guard that cannot
 * go red is not a guard, and a rule written twice is a rule that will be edited
 * once. Expiry now happens in exactly one place — the per-key check — and this
 * function does only the job its name claims.
 *
 * The change is also strictly cheaper: the old sweep walked the entire Map on
 * every single request; this walks it only when it is oversized.
 */
function evictIfCrowded(now) {
  if (buckets.size <= MAX_TRACKED_KEYS) return;
  for (const [key, bucket] of buckets) {
    if (bucket.resetAt <= now) buckets.delete(key);
  }
  if (buckets.size <= MAX_TRACKED_KEYS) return;
  const byResetAt = [...buckets.entries()].sort((a, b) => a[1].resetAt - b[1].resetAt);
  for (const [key] of byResetAt.slice(0, buckets.size - MAX_TRACKED_KEYS)) {
    buckets.delete(key);
  }
}

/**
 * Derive a bucket key from what the request actually carries.
 *
 * Order is deliberate — see the identity note above. The forwarded IP is
 * preferred over the client-supplied session id because the client controls the
 * latter completely. `anon` is the floor: it pools every unidentifiable caller
 * into one bucket, which is the correct fail-CLOSED direction for a paid
 * backend, and in practice only happens in local dev where no proxy sets
 * x-forwarded-for and the client has not yet minted a session.
 */
export function rateLimitKeyFrom({ forwardedFor, realIp, sessionId } = {}) {
  const ip = String(forwardedFor || '').split(',')[0].trim() || String(realIp || '').trim();
  if (ip) return `ip:${ip}`;
  const sid = String(sessionId || '').trim();
  if (sid) return `sid:${sid.slice(0, 100)}`;
  return 'anon';
}

/**
 * Count one hit against `key`.
 *
 * `now` is injectable so the window boundary can be exercised without fake
 * timers. Returns the decision plus what a 429 needs to answer honestly.
 */
export function checkRateLimit(key, options = {}) {
  const {
    windowMs = DEFAULT_WINDOW_MS,
    max = DEFAULT_MAX,
    now = Date.now(),
  } = options;

  evictIfCrowded(now);

  // THE ONE PLACE the window is released. Do not add a second — see the note on
  // evictIfCrowded for what happened last time there were two.
  const existing = buckets.get(key);
  if (!existing || existing.resetAt <= now) {
    buckets.set(key, { count: 1, resetAt: now + windowMs });
    return { allowed: true, remaining: max - 1, retryAfterSeconds: 0 };
  }

  existing.count += 1;
  const retryAfterSeconds = Math.max(1, Math.ceil((existing.resetAt - now) / 1000));

  if (existing.count > max) {
    return { allowed: false, remaining: 0, retryAfterSeconds };
  }
  return { allowed: true, remaining: max - existing.count, retryAfterSeconds };
}

/** Test/dev affordance. Never called by the routes. */
export function __resetRateLimitBuckets() {
  buckets.clear();
}
