import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readSource, walkSources } from '../sourceScan.mjs';

/**
 * A `fixed inset-0` OVERLAY MUST NOT BE A CHILD OF A `space-y-*` WRAPPER.
 *
 * ── THE DEFECT ──────────────────────────────────────────────────────────────
 * Every modal on /admin/schedules rendered with a white band across the top of
 * the screen — the overlay did not cover the viewport. DevTools reported the
 * overlay as 2560x1261 with `margin: 16px 0px 0px`, and `inset-0` cannot
 * produce a margin.
 *
 * `space-y-4` compiles to (verified with the real Tailwind config):
 *
 *     .space-y-4 > :not([hidden]) ~ :not([hidden]) {
 *       margin-top: calc(1rem * calc(1 - var(--tw-space-y-reverse)));
 *     }
 *
 * — a rule about CHILDREN. The modal was rendered inside the page's
 * `<div className="space-y-4 p-1">`, so it was one of those children and took
 * the 16px. `inset-0` sets top AND bottom to 0 while height stays auto, which
 * is over-constrained: the margin wins, the fixed layer is pushed down, and its
 * resolved height shrinks by exactly the margin. `space-y-6` screens showed a
 * 24px band by the same mechanism.
 *
 * ── WHY THE GUARD IS "NOT A CHILD" AND NOT "HAS mt-0" ───────────────────────
 * An `!mt-0` on each overlay would also work and would be the wrong fix: it
 * treats the symptom on one element, and the next wrapper to gain any margin
 * utility re-breaks it somewhere else. A SIBLING cannot be reached by
 * `space-y-*` at all, so the relationship is what is asserted.
 *
 * ── SCOPE ───────────────────────────────────────────────────────────────────
 * Only overlays declared INSIDE the same component as the wrapper are visible
 * to a source scan, which is exactly the family that had the bug. An overlay
 * that lives in its own component and is INVOKED as a child of a spacer is the
 * other shape (InstructorsAdminClient was one); that is covered by the
 * invocation sweep below.
 */

/** Every admin client that declares a full-viewport overlay. */
function overlayFiles() {
  return walkSources('src/app/admin').filter((f) => /fixed inset-0 z-50/.test(f.code));
}

/**
 * Does `code` render `needle` while a `space-y-*` wrapper is still open?
 *
 * Brace/indent parsing of JSX is not worth the complexity here. The reliable
 * structural signal is INDENTATION: the wrapper opens at some indent, and any
 * line at a DEEPER indent before its matching close is inside it. Both are
 * generated by the same formatter, so this is stable — and the control at the
 * bottom proves the probe can see the defect it bans.
 */
function insideSpacer(code, needleRe) {
  const lines = code.split('\n');
  for (let i = 0; i < lines.length; i += 1) {
    const open = /^(\s*)<div className="[^"]*\bspace-y-\d/.exec(lines[i]);
    if (!open) continue;
    const indent = open[1].length;
    for (let j = i + 1; j < lines.length; j += 1) {
      const line = lines[j];
      if (line.trim() === '') continue;
      const at = line.search(/\S/);
      // Back out to the wrapper's own level or shallower → it has closed.
      if (at <= indent) break;
      if (needleRe.test(line)) return { wrapperLine: i + 1, hitLine: j + 1 };
    }
  }
  return null;
}

test('no admin overlay is DECLARED inside a space-y-* wrapper', () => {
  const offenders = [];
  for (const f of overlayFiles()) {
    const hit = insideSpacer(f.code, /fixed inset-0 z-50/);
    if (hit) offenders.push(`${f.rel}: overlay at line ${hit.hitLine} is inside the space-y wrapper at line ${hit.wrapperLine}`);
  }
  assert.deepEqual(
    offenders,
    [],
    'a fixed overlay inside a space-y-* wrapper gets margin-top and leaves a band '
      + 'of page across the top of the viewport:\n  ' + offenders.join('\n  '),
  );
});

test('nor is a modal COMPONENT invoked inside one', () => {
  /**
   * The second shape, and the one InstructorsAdminClient had: the overlay lives
   * in `<InstructorModal>` further down the file, so a scan for the overlay
   * markup finds nothing inside the wrapper — but the RENDER SITE is still a
   * child of it and the margin still lands.
   *
   * Matched on the naming convention this admin uses (`<XxxModal`), which is
   * what every one of these components is called.
   */
  const offenders = [];
  for (const f of overlayFiles()) {
    const hit = insideSpacer(f.code, /<\w*Modal\b/);
    if (hit) offenders.push(`${f.rel}: modal rendered at line ${hit.hitLine} inside the space-y wrapper at line ${hit.wrapperLine}`);
  }
  assert.deepEqual(offenders, [], offenders.join('\n  '));
});

test('the four screens that HAD the band render their modal as a sibling', () => {
  /**
   * Named explicitly, because the sweeps above are absences: if `overlayFiles`
   * ever stopped matching, both would pass over an empty list. These four are
   * the ones measured as broken, and each must still show the fixed shape —
   * a fragment root with the spacer closed before the modal.
   */
  const FIXED = [
    'src/app/admin/schedules/_components/SchedulesAdminClient.jsx',
    'src/app/admin/instructors/_components/InstructorsAdminClient.jsx',
    'src/app/admin/career-paths/_components/CareerPathsAdminClient.jsx',
    'src/app/admin/career-path-registrations/_components/CareerPathRegistrationsClient.jsx',
  ];
  for (const rel of FIXED) {
    const { code } = readSource(rel);
    assert.match(code, /return \(\s*\n\s*<>/, `${rel} no longer returns a fragment root`);
    assert.equal(
      insideSpacer(code, /fixed inset-0 z-50|<\w*Modal\b/),
      null,
      `${rel} put its modal back inside the space-y wrapper`,
    );
  }
});

// ── Controls ────────────────────────────────────────────────────────────────

test('CONTROL: the probe DOES fire on the exact shape that was broken', () => {
  /**
   * Every assertion above is an absence. Run against the real pre-fix shape —
   * a `space-y-4` wrapper with the overlay as a later child — the probe must
   * report it, or the sweeps mean nothing.
   */
  const broken = [
    '  return (',
    '    <div className="space-y-4 p-1">',
    '      <div className="header" />',
    '      {modal && (',
    '        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">',
    '          <div />',
    '        </div>',
    '      )}',
    '    </div>',
    '  );',
  ].join('\n');
  const hit = insideSpacer(broken, /fixed inset-0 z-50/);
  assert.ok(hit, 'the probe cannot see an overlay nested in a space-y wrapper');
  assert.equal(hit.wrapperLine, 2);
  assert.equal(hit.hitLine, 5);

  // …and on the component-invocation variant.
  const brokenInvoke = [
    '    <div className="space-y-6">',
    '      <div className="cards" />',
    '      {editing && (',
    '        <InstructorModal onClose={x} />',
    '      )}',
    '    </div>',
  ].join('\n');
  assert.ok(insideSpacer(brokenInvoke, /<\w*Modal\b/), 'the probe misses an invoked modal');
});

test('CONTROL: the probe does NOT fire on the fixed shape', () => {
  // The sibling arrangement, which is what all four now ship.
  const fixed = [
    '  return (',
    '    <>',
    '      <div className="space-y-4 p-1">',
    '        <div className="header" />',
    '      </div>',
    '      {modal && (',
    '        <div className="fixed inset-0 z-50" />',
    '      )}',
    '    </>',
    '  );',
  ].join('\n');
  assert.equal(insideSpacer(fixed, /fixed inset-0 z-50/), null, 'a sibling overlay must not be reported');
});

test('CONTROL: the sweep is reading real files, not an empty list', () => {
  const files = overlayFiles();
  assert.ok(files.length >= 8, `only ${files.length} admin overlays found — the sweep is not reading the tree`);
  for (const f of files) assert.ok(f.code.length > 200, `${f.rel} was not actually read`);
});
